import { useState } from "react";

export default function EthicsModal() {
  const [open, setOpen] = useState(false);

  return (
    <>
      <button className="ethics-trigger" onClick={() => setOpen(true)}>
        🔒 Ethical AI Safeguards
      </button>

      {open && (
        <div className="modal-overlay" onClick={() => setOpen(false)}>
          <div className="modal-box" onClick={(e) => e.stopPropagation()}>
            <div className="modal-header">
              <span>🔒 Ethical AI Safeguards</span>
              <button className="modal-close" onClick={() => setOpen(false)}>✕</button>
            </div>

            <div className="modal-sections">
              <div className="ethics-item">
                <div className="ethics-badge privacy">Data Privacy</div>
                <p>All user data and property inputs are encrypted in transit and at rest. We do not sell or share user data with third parties. MongoDB stores only the minimum data required for functionality.</p>
              </div>

              <div className="ethics-item">
                <div className="ethics-badge bias">Bias Acknowledgment</div>
                <p>Our XGBoost model is trained on publicly available datasets from Gurgaon, Hyderabad, Kolkata, and Mumbai. It may underperform for cities not represented in training data. Predictions should be treated as advisory, not authoritative.</p>
              </div>

              <div className="ethics-item">
                <div className="ethics-badge disclaimer">AI Disclaimer</div>
                <p>BrickIQ recommendations are generated by machine learning models and are not financial or legal advice. Always conduct independent due diligence before making investment decisions. ROI estimates are model outputs, not guaranteed returns.</p>
              </div>

              <div className="ethics-item">
                <div className="ethics-badge transparency">Transparency</div>
                <p>Every recommendation includes an explainability section that outlines the key factors influencing the decision. We believe AI systems should be understandable and contestable.</p>
              </div>
            </div>
          </div>
        </div>
      )}

      <style>{`
        .ethics-trigger {
          background: rgba(255,255,255,0.04);
          border: 1px solid rgba(255,255,255,0.1);
          color: rgba(255,255,255,0.5);
          font-size: 12px; padding: 6px 14px; border-radius: 8px;
          cursor: pointer; transition: all 0.2s;
        }
        .ethics-trigger:hover { color: #fff; border-color: rgba(255,255,255,0.2); }

        .modal-overlay {
          position: fixed; inset: 0; z-index: 100;
          background: rgba(0,0,0,0.7);
          display: flex; align-items: center; justify-content: center;
          backdrop-filter: blur(4px);
          animation: fadeIn 0.2s ease;
        }
        @keyframes fadeIn { from{opacity:0} to{opacity:1} }

        .modal-box {
          width: 520px; max-width: 90vw;
          background: #0d1520;
          border: 1px solid rgba(255,255,255,0.1);
          border-radius: 16px; overflow: hidden;
          animation: slideUp 0.3s cubic-bezier(0.16,1,0.3,1);
        }
        @keyframes slideUp { from{transform:translateY(20px);opacity:0} to{transform:translateY(0);opacity:1} }

        .modal-header {
          display: flex; align-items: center; justify-content: space-between;
          padding: 18px 22px;
          border-bottom: 1px solid rgba(255,255,255,0.06);
          font-size: 15px; font-weight: 600; color: #fff;
        }
        .modal-close {
          background: none; border: none; color: rgba(255,255,255,0.4);
          font-size: 16px; cursor: pointer; padding: 2px 6px;
          border-radius: 4px; transition: color 0.2s;
        }
        .modal-close:hover { color: #fff; }

        .modal-sections { padding: 20px 22px; display: flex; flex-direction: column; gap: 16px; }

        .ethics-item { display: flex; flex-direction: column; gap: 6px; }
        .ethics-badge {
          font-size: 11px; font-weight: 700; letter-spacing: 0.8px;
          text-transform: uppercase; padding: 3px 10px;
          border-radius: 6px; width: fit-content;
        }
        .privacy { background: rgba(0,200,150,0.12); color: #00c896; }
        .bias { background: rgba(255,170,0,0.12); color: #ffaa00; }
        .disclaimer { background: rgba(255,100,100,0.12); color: #ff6464; }
        .transparency { background: rgba(0,119,255,0.12); color: #4da6ff; }
        .ethics-item p { font-size: 13px; color: rgba(255,255,255,0.5); line-height: 1.6; }
      `}</style>
    </>
  );
}
