import React from 'react';
import { X, ShieldCheck, Scale, Eye } from 'lucide-react';

export default function EthicsModal({ onClose }) {
  return (
    <div style={{ position: 'fixed', top: 0, left: 0, right: 0, bottom: 0, background: 'rgba(0,0,0,0.6)', backdropFilter: 'blur(5px)', zIndex: 100, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
      <div className="glass-card animate-slide-up" style={{ padding: '2.5rem', maxWidth: '600px', width: '90%', position: 'relative' }}>
        <button onClick={onClose} style={{ position: 'absolute', top: '1.5rem', right: '1.5rem', background: 'transparent', border: 'none', color: '#fff', cursor: 'pointer' }}>
          <X />
        </button>
        
        <h2 style={{ display: 'flex', alignItems: 'center', gap: '0.75rem', marginTop: 0 }}>
          <ShieldCheck color="#10b981" /> Transparent AI Guidelines
        </h2>
        
        <div style={{ marginTop: '2rem', display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>
          <div style={{ display: 'flex', gap: '1rem', alignItems: 'flex-start' }}>
            <Scale color="#3b82f6" style={{ flexShrink: 0, marginTop: '2px' }} />
            <div>
              <h4 style={{ margin: '0 0 0.5rem 0' }}>Bias Acknowledgment</h4>
              <p style={{ margin: 0, opacity: 0.7, fontSize: '0.9rem', lineHeight: 1.5 }}>
                Our algorithms are trained on historical market data which may inherit past socio-economic biases. BrickIQ continuously audits data subsets to neutralize redlining and promote fair development opportunities.
              </p>
            </div>
          </div>

          <div style={{ display: 'flex', gap: '1rem', alignItems: 'flex-start' }}>
            <Eye color="#3b82f6" style={{ flexShrink: 0, marginTop: '2px' }} />
            <div>
              <h4 style={{ margin: '0 0 0.5rem 0' }}>Data Privacy & Aggregation</h4>
              <p style={{ margin: 0, opacity: 0.7, fontSize: '0.9rem', lineHeight: 1.5 }}>
                Buyer details and builder financial assets are strictly end-to-end encrypted. Aggregated market predictions protect exact parcel ownership and maintain full GDPR-compliance.
              </p>
            </div>
          </div>
          
          <div style={{ background: 'rgba(239,68,68,0.1)', padding: '1rem', borderRadius: '8px', border: '1px solid rgba(239,68,68,0.2)' }}>
            <h4 style={{ margin: '0 0 0.5rem 0', color: '#fca5a5' }}>Predictive Disclaimer</h4>
            <p style={{ margin: 0, opacity: 0.8, fontSize: '0.85rem', color: '#fecaca' }}>
              ROI percentages are algorithmic estimations generated by XGBoost Regressors. Actual yields fluctuate based on macroeconomics. This data serves as decision-support, not financial advice.
            </p>
          </div>
        </div>

        <button onClick={onClose} className="primary-btn" style={{ width: '100%', marginTop: '2rem' }}>I Understand</button>
      </div>
    </div>
  );
}
